version: "3.8"

services:
  client:
    restart: always
    container_name: portfolio-client-dev
    build:
      context: ../../../app/client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
    ports:
      - 3000:3000
